// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:rulewise/config/api_config.dart';



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ApiConfig.firebaseWebApiKey,
    appId: '1:638906676810:web:2c6904c21b87dc14e558b3',
    messagingSenderId: '638906676810',
    projectId: 'rulewise-4ec59',
    authDomain: 'rulewise-4ec59.firebaseapp.com',
    storageBucket: 'rulewise-4ec59.firebasestorage.app',
    measurementId: 'G-ELDHLQ81TC',
  );



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ApiConfig.firebaseAndroidApiKey,
    appId: '1:638906676810:android:19d0e0af0643e725e558b3',
    messagingSenderId: '638906676810',
    projectId: 'rulewise-4ec59',
    storageBucket: 'rulewise-4ec59.firebasestorage.app',
  );



  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: 'dummy-app-id',
    messagingSenderId: 'dummy-sender-id',
    projectId: 'dummy-project-id',
    storageBucket: 'dummy-project-id.appspot.com',
    iosClientId: 'dummy-ios-client-id',
    iosBundleId: 'com.example.rulewise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: 'dummy-app-id',
    messagingSenderId: 'dummy-sender-id',
    projectId: 'dummy-project-id',
    storageBucket: 'dummy-project-id.appspot.com',
    iosClientId: 'dummy-ios-client-id',
    iosBundleId: 'com.example.rulewise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: ApiConfig.firebaseWindowsApiKey,
    appId: '1:638906676810:web:fd91746b1b2795c8e558b3',
    messagingSenderId: '638906676810',
    projectId: 'rulewise-4ec59',
    authDomain: 'rulewise-4ec59.firebaseapp.com',
    storageBucket: 'rulewise-4ec59.firebasestorage.app',
    measurementId: 'G-W443NZKB4K',
  );


}
